name: 'Github GraphQL queries for dfb'
description: 'GraphQL queries to better understand state and value of repositories'
author: 'dfberry'
inputs:
  github_personal_access_token: 
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  query_type: 
    required: false
    description: 'name of graphql query such as `whoami` or `org-repos-extended` or `user_repos_extended`'
    default: 'whoami'
  repoOwnerType: 
    required: false
    description: '`organization` or `user`'
    default: 'organization'
  github_org: 
    required: false
    description: 'input GitHub org - PAT must have permission to org. If user, then must be user account.'
    default: 'Azure-Samples'
  save_to_file: 
    required: false
    description: 'Save output to file instead of output data to save runtime memory.'
    default: 'true'    
  save_to_file_name: 
    required: false
    description: 'Output file name. Default is graphql_data.json'
    default: 'graphql_data.json'  
  max_items:
    required: false
    description: 'If returning an array from the `query_type`, limit results to `max_items` count. Default is 10.'
    default: '10' 
  max_page_size:
    required: false
    description: 'Page size used in query, if query can return a page. Default is 100.'
    default: '100'  
  rate_limit_delay:
    required: false
    description: 'If paging, use rate limit to stay within rate limits. Time in milliseconds. Default is 30000.'
    default: '30000'    
runs:
  using: 'node16'
  main: 'package/index.js'
