name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github_personal_access_token: 
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  query_type: 
    required: false
    description: 'name of graphql query such as `whoami` or `org-repos`'
    default: 'whoami'
  github_org: 
    required: false
    description: 'input GitHub org - PAT must have permission to org'
    default: 'Azure-Samples'
runs:
  using: 'node16'
  main: 'package/index.js'
